close all
clear all
clc

% input = struct(...
%     'a', 120, ...
%     'b', 70, ...
%     'h', 48, ...
%     'hx', 30 ...
% );
% 
% poleOffset = 5; % расстояние от границы ПС до молниеприемника
% o = poleOffset;
% 
% poles = {...
%     struct('x', o, 'y', o),...
%     struct('x', o + 35, 'y', o),...
%     struct('x', o + 75, 'y', o),...
%     struct('x', input.a - o, 'y', o),...
%     struct('x', o, 'y', input.b - o),...
%     struct('x', o + 35, 'y', input.b - o),...
%     struct('x', o + 75, 'y', input.b - o),...
%     struct('x', input.a - o, 'y', input.b - o)...
% };

input = struct(...
    'a', 70, ...
    'b', 100, ...
    'h', 40, ...
    'hx', 20 ...
);

poleOffset = 5; % расстояние от границы ПС до молниеприемника
o = poleOffset;

poles = {...
    struct('y', o, 'x', o),...
    struct('y', o + 45, 'x', o),...
    struct('y', input.b - o, 'x', o),...
    struct('y', o, 'x', input.a - o),...
    struct('y', o + 45, 'x', input.a - o),...
    struct('y', input.b - o, 'x', input.a - o)...
};

rx = singlePoleArea(input.h, input.hx);
x = sin(0:0.01:2*pi)*rx;
y = cos(0:0.01:2*pi)*rx;
dummyX = cellfun(@(pole) pole.x + x, poles, 'uniformoutput', false);
dummyY = cellfun(@(pole) pole.y + y, poles, 'uniformoutput', false);
polesAreasX = [];
polesAreasY = [];
for I = 1:length(poles)
    polesAreasX = [polesAreasX dummyX{I} NaN];
    polesAreasY = [polesAreasY dummyY{I} NaN];
end


subStation = struct(...
    'x', [0 0 input.a, input.a 0], ...
	'y', [0 input.b, input.b, 0 0]...
);

figure
hold on 

plot(subStation.x, subStation.y, '-b', ...
    cellfun(@(pole) pole.x, poles), cellfun(@(pole) pole.y, poles), '*b', ...
    polesAreasX, polesAreasY, 'r-' ...
);

xlim(input.a*[-0.25 1.25]);
ylim(input.b*[-0.25 1.25]);
axis('equal')

for I = 1: length(poles)-1
    for J = I+1: length(poles)
        [x, y, clr] = twoPolesArea(poles{I}, poles{J}, input.h, input.hx);
        set(gca, 'children',flipud(get(gca, 'children')))
        fill(x, y, clr, 'facealpha', 0.35, 'edgecolor','none');
        set(gca, 'children',flipud(get(gca, 'children')))
    end
    pause;
end


